export const ADD_PRODUCT = 'PRODUCT/ADD_PRODUCT';
export const UPDATE_PRODUCT = 'PRODUCT/UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'PRODUCT/DELETE_PRODUCT';
export const GET_PRODUCT = 'PRODUCT/GET_PRODUCT';

export const DELETE_PRODUCT_CART = 'CART/DELETE_PRODUCT_CART';
export const ADD_PRODUCT_CART = 'CART/ADD_PRODUCT_CART';
export const UPDATE_COUNT_PRODUCT_CART = 'CART/UPDATE_COUNT_PRODUCT_CART';

export const SHOW_ERROR_ALERT = 'ALERT/SHOW_ERROR';
export const SHOW_INFO_ALERT = 'ALERT/SHOW_INFO';
export const SHOW_SUCCESS_ALERT = 'ALERT/SHOW_SUCCESS'
export const CLOSE_ALERT = 'ALERT/CLOSE';
